package com.todoplus.exporter

/**
 * User-configurable overrides for the HTML export.
 *
 * Each field defaults to an empty string, which tells [TodoExporter] to use
 * its own built-in defaults.  When the user provides a non-blank value it is
 * injected verbatim into the corresponding section of the generated HTML.
 *
 * Section mapping (mirrors the three sb.append blocks in TodoExporter):
 *  - [pageTitle]            → <title> tag content
 *  - [customCss]            → injected into <style> block (after base styles)
 *  - [statsHtmlOverride]    → replaces the entire <div class="stats"> block
 *  - [listHtmlOverride]     → replaces the <table>…</table> block (row rows still generated by default if blank)
 *  - [footerHtml]           → inserted just before </body>
 */
data class HtmlExportConfig(
    /** Replaces the default page / header title "TODO++ Dashboard". */
    var pageTitle: String = "",

    /**
     * Extra CSS injected inside the <style> block after the built-in rules.
     * Useful for overriding colours for criticality levels, fonts, etc.
     *
     * Example:
     *   :root { --critical: #e53935; --high: #fb8c00; }
     */
    var customCss: String = "",

    /**
     * Full HTML override for the stats counter cards at the top of the report.
     * When blank the default four stat-cards (Total / Critical / High / Medium / Low)
     * are rendered.
     *
     * Placeholder tokens supported:
     *   {{TOTAL}}, {{CRITICAL}}, {{HIGH}}, {{MEDIUM}}, {{LOW}}
     */
    var statsHtmlOverride: String = "",

    /**
     * Full HTML override for the list/table section.
     * When blank the default sortable <table> with all rows is rendered.
     *
     * Placeholder tokens supported:
     *   {{ROWS}} – inserts the auto-generated <tr> rows
     */
    var listHtmlOverride: String = "",

    /**
     * HTML appended at the very bottom of <body>, just before </body>.
     * Intended for a footer, watermark, or extra script tag.
     *
     * Example:
     *   <footer style="margin-top:40px;text-align:center;color:#555">
     *     Generated by MyTeam CI pipeline
     *   </footer>
     */
    var footerHtml: String = ""
) {
    /** Returns true when no field has been customised. */
    fun isDefault(): Boolean =
        pageTitle.isBlank() && customCss.isBlank() && statsHtmlOverride.isBlank() &&
                listHtmlOverride.isBlank() && footerHtml.isBlank()

    companion object {
        /** Convenience factory for the built-in defaults (no overrides). */
        fun default(): HtmlExportConfig = HtmlExportConfig()
    }
}
